title: Zhong's Blog
description: "This is Zhong in the house."
author:
  name: "2h0ng"
  email: "superboyzjc@gmail.com"
  url: "https://blog.2h0ng.wiki"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/
google_analytics: G-JRNNF9TMHE

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "2h0ng"
year : "2024"
